---
# ############
# Etcd tasks
# ############
- name: create etcd-member systemd customization directory
  file: name={{item}} state=directory
  with_items:
  - /etc/systemd/system/etcd-member.service.d/

- name: Install etcd-member service settings
  template:
    src: "{{playbook_dir}}/{{role_dir}}/files/templates/cluster.conf.j2"
    dest: /etc/systemd/system/etcd-member.service.d/cluster.conf
  register: etcd_conf

- name: Reloading daemon
  command: "systemctl daemon-reload"
  when: etcd_conf.changed

- name: Restarting etcd-member service if needed
  service: name=etcd-member state=restarted
  when: etcd_conf.changed

- name: Ensure etcd-member service is started
  service: name=etcd-member state=started
  when: not etcd_conf.changed

- name: Ensure etcd-member is started on boot
  service: name=etcd-member enabled=yes
